### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by SuperAdam47** [SoraCrafty/GunServer#11]
[11:48:15] [Server thread/CRITICAL]: Error: "Call to undefined function gun\player\skin\imagecreatefrompng()" (EXCEPTION) in "plugins/gun/src/gun/player/skin/SkinStrage" at line 29

**Comment by kurarin1** [comment]
This project is Closed.
sorry😭

**Comment by ghost** [comment]
水素水

**Comment by muku787** [comment]
🤔

**Comment by SuperAdam47** [comment]
Why??

**Comment by SuperAdam47** [comment]
Fix pr please

**Comment by kurarin1** [comment]
If we fix this error,This plugin wouldn't be work.
Because this plugin(and resourcepacks) was made for minecrafBE ver 1.11, so it have many bugs and errors now(now ver is 1.12).
We stopped developping this plugin long ago and developers are busy so we don't have time to fix this plugin.
sorry.

**Comment by SuperAdam47** [comment]
Understood :(
