### ISSUE TITLE
playerData.phpの65行目でエラーが出る

### ISSUE THREAD

**Issue by kurarin1** [SoraCrafty/GunServer#4]
#3 @muku787 
Error: Call to a member function updateScoreBoard() on null
File: Gun/src/gun/data/playerData
Line: 65
Type: Error

65行目
`
$this->SC->updateScoreBoard($name, $data, $this->plugin->getServer()->getPlayer($username));
`

スコアボード関連のバグ(?)

**Comment by muku787** [comment]
scoreboardのインスタンスが作られるより前にplayerdataのインスタンスが作られて$this->SCがぬるになってたせいだった
修正した！
